name: roz
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pysam
  - minimap2
  - mappy
  - pika
  - samtools
  - pytest
  - biopython
  - fastapi
  - sqlite
  - requests
  - pandas
  - sqlmodel
  - boto3